<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.hiero.ecom</groupId>
        <artifactId>hiero-ecom</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>hiero-ecom.ui.apps</artifactId>
    <packaging>content-package</packaging>
    <name>Hiero eCommerce - UI Apps</name>
    <build>
        <plugins>
            <plugin>
                <groupId>com.day.jcr.vault</groupId>
                <artifactId>content-package-maven-plugin</artifactId>
                <version>1.0.4</version>
                <extensions>true</extensions>
                <configuration>
                    <group>com.hiero.ecom</group>
                    <name>hiero-ecom-ui-apps</name>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>unpack-ui-frontend</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.hiero.ecom</groupId>
                                    <artifactId>hiero-ecom.ui.frontend</artifactId>
                                    <version>${project.version}</version>
                                    <classifier>clientlib</classifier>
                                    <type>zip</type>
                                    <outputDirectory>${project.basedir}/src/main/content/jcr_root/apps/hiero-ecom/ui.frontend.clientlibs</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>